name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: "20"

    - name: Install dependencies
      run: npm ci # If you have a package-lock.json, use `npm ci` instead of `npm install` for faster installation

    - name: Run tests
      run: npm run lint

    - name: Run tests
      run: npm run test

